First release candidate
Xon/XenForo2-CanWarnStaff pull request #1
Opened 2018-01-05 17:45 UTC by yugensoft

Each part tested as working in XF2

2018-01-05 19:47 UTC, Xon commented
@yugensoft please extend the Post repository `findPostsForThreadView`/`findNewestPostsInThread`/`findNextPostsInThread` in  to include `Post.User.PermissionCombination` IF the user has the "warn" permission.

This reduces the N+1-like query behaviour and means normal users will not impact the number of queries per thread page

2018-01-05 19:52 UTC, Xon commented
Also extend `addCommentsToProfilePosts` to fetch `PermissionCombination`'s for unique users for a single extra query

2018-01-05 20:04 UTC, Xon requested changes

2018-01-05 20:04 UTC, Xon commented on upload/src/addons/SV/CanWarnStaff/XF/Entity/User.php
> +		return \XF::visitor()->canReport($error);
I prefer to avoid outright overriding functions like this, and instead would prefer this to be a call to the parent followed by doing this logic (if the current user entity is staff, and the above results are false).

This avoids weird behaviour for other add-ons extending this class

2018-01-05 20:04 UTC, Xon commented on upload/src/addons/SV/CanWarnStaff/XF/Entity/Warning.php
> +class Warning extends XFCP_Warning {
This class is extended in a way which makes other add-ons extending difficult to override. The XF1 version calls the parent functions, and then applies the add-on logic after.

2018-01-05 20:04 UTC, Xon commented on upload/src/addons/SV/CanWarnStaff/XF/Service/Thread/ReplyBan.php
> +	protected function _validate()
Would prefer to call `parent::_validate()` and then unset `$errors['is_staff']` where required. Bit simpler and avoids issues with classes extending this

2018-01-06 05:29 UTC, yugensoft commented
Understood, I'll make those revisions.

2018-01-08 11:48 UTC, yugensoft commented
Alright I made the revisions, let me know if that's what you had in mind. The caching can't be done exactly the same as in XF1, as for instance, findPostsForThreadView() is passing back a finder not an array.

2018-01-08 16:55 UTC, merged

2018-01-08 17:29 UTC, Xon commented
LGTM thanks.

I pushed some minor changes Attachment Repo's addAttachmentsToContent() is a better attachment point to extract the caching/preloading rather than fiddling with the post finder.